<?php include APPPATH . 'views/tpl.header.phtml';?>

    <ul class="nav nav-tabs">
        <li  class="active">
            <a href="/index.php?c=leimu&a=leimulist">类目列表</a>
        </li>
        <li>
            <a href="/index.php?c=leimu&a=addleimu">添加类目</a>
        </li>
    </ul>

    <form method="post" action="">
        <fieldset>
            <legend>类目添加</legend>
            <input type="hidden" name="lid" id="lid" value="" />
            <label>类目名称</label>
            <input type="text" name="lname" id="lname" placeholder="请输入类目名称">
            <span class="help-block">请输入类目名称.</span>

            <label>父类ID</label>
            <select name="pid" id="pid">
                <option value="0">请选择父类</option>
                <?php foreach($leimuList as $list){
                    echo "<option value='{$list['lid']}'>{$list['lname']}</option>";
                }?>
            </select>
            <span class="help-block">请选择所属父类.</span>
            <label>排序</label>
            <input type="text" name="ob" id="ob" value="0"/>
            <span class="help-block">排序顺序为从小到大.</span>
            <label>状态</label>
            <label><input type="radio" name="status" value="1" checked /> 启用</label>
            <label><input type="radio" name="status" value="0" /> 禁用</label>
            <br/>
            <button type="submit" class="btn btn-primary">修改</button>
        </fieldset>
    </form>

<script type="text/javascript">
    $(document).ready(function(){
        $('#lid').val('<?php echo $leimuInfo["lid"];?>');
        $('#lname').val('<?php echo $leimuInfo["lname"];?>');
        $('#pid').val('<?php echo $leimuInfo["pid"];?>');
        $('#ob').val('<?php echo $leimuInfo["ob"];?>');
        $("input[@type=radio][name=status][value=<?php echo $leimuInfo['status'];?>]").attr("checked","checked");
    });
</script>


<?php include APPPATH . 'views/tpl.footer.phtml'?>