
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>XX美图网</title>
    <link href="/static/css/bootstrap.css" rel="stylesheet" type="text/css" />
    <link href="/static/css/bootstrap-responsive.css" rel="stylesheet" type="text/css" />
    
    <script type="text/javascript" src="/static/js/1.9.1.min.js"></script>
    <script type="text/javascript" src="/static/js/bootstrap.js"></script>
    <style type="text/css">
        body {
            margin: 10px;
        }
    </style>
</head>
<body>